{% set name = "reducer" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d9e27276ab9c29230a187192ad0849bb6fa72e1d6e4d395c3b4fd18f2edb148

build:
  noarch: python
  number: 0
  entry_points:
    - reducer = reducer:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - astropy >=2.0
    - numpy
    - scipy
    - scikit-image
    - ipywidgets >=7
    - msumastro >=0.9
    - ccdproc >=1.2
    - matplotlib-base
    - dask

test:
  imports:
    - reducer
  commands:
    - reducer --help

about:
  home: http://reducer.readthedocs.org
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Jupyter widget-based package for reducing FITS images
  description: |
    reducer provides a a widget interface in a Jupyter notebook to the ccdproc package
    for calibrating astronomical images.
  doc_url: http://reducer.readthedocs.org
  dev_url: https://github.com/mwcraig/reducer

extra:
  recipe-maintainers:
    - mwcraig
