{% set name = "reducer" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 316e88ba2bd9349e15c8c5f110c445889f301eb4eb2e346addfe917135700ea7

build:
  noarch: python
  number: 0
  entry_points:
    - reducer = reducer:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - astropy >=4
    - numpy
    - scipy
    - scikit-image
    - ipywidgets >=7.5
    - msumastro >=1
    - ccdproc >=2
    - matplotlib-base
    - dask

test:
  imports:
    - reducer
  commands:
    - reducer --help

about:
  home: http://reducer.readthedocs.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Jupyter widget-based package for reducing FITS images
  description: |
    reducer provides a a widget interface in a Jupyter notebook to the ccdproc package
    for calibrating astronomical images.
  doc_url: http://reducer.readthedocs.org
  dev_url: https://github.com/mwcraig/reducer

extra:
  recipe-maintainers:
    - mwcraig
