travis:
  secure:
    BINSTAR_TOKEN: 1J+XeTfoLB73RXavkJiKaWCf9CpfesmLsdxhUF6cIgzKLhzaugLCQkwo4WeYqEudRVBwilVVFxKMmZnq26oiHhJdj5vjjqxQvAxmgaSbXmS27/D+6odpp98RCGXtaKHyuXmXLJP0wnX69hCTCfUuzMeoGRmngBRgeUTkkoWTNkiFtt/C+Lfz4KvMes0n9ozuEU8ZV0AXW04EigQ/YtBzqrCBoUYn+ICaUIXRM0VX5Zz/+zIIsMH7PQy2pxPD1es/2h1BswDmjQ00PC+vPWLpCbhZvoWzlckF72NVunRMs4Pq7zHdEiM9XM9MnF/0W2/46oCB2hyzVtzTTMCmtvnFAPVXEU+IkQVepwgtFu8Egim0sRCSBbibqN4pqZrfxQGIDds/5JX6xMAN6GN8eQwjyQP2sSGohiDWgSRSh86/Ldbj0Vg/YRXWE5J3UsXdt73uVrM6Z0niQLi5RiCUDPxzkmcNjPuIMzzDZh8mD3RFoL0CMfILVbyAnkTpOWudXW408HOu9b58r6dFm2SgSxhWoy7ARgVDO/PbwETM8jxmwalx/GBcHCneZSjSaVDs7Gxj+PjQvCFj5EFkmyVmSBhmO6vBTR775TekUGv8dBe03qVV+OXl7qXTEoWmVAHxS1uIaYn8c6nxLU1iL5lInNaNAY/pfGwlljqYin0gVrjzNpo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
