travis:
  secure:
    BINSTAR_TOKEN: mFkD3Di76lhv6OO/NiGqJivNV/ILDmN2nOlQ9e01Mv9r1hApnD2BuCkfI5B499CZCIOsxnyRqEOGHH+WhY/ilpOtg/C4HSSQ9J97EEiUBFy5MZW3E1k/cyL0YabSPq6pOt5u/5Ev8r8Dvwj082yN8hulKM+bWrgOO9e+HDIC1ZwIAW3uUPkPgkc3IPRa9ptamJSqr1ODSez1WpGKA0mdPqNPNMJ7ZRLJuldkKuV8gS4PyN9bUKYcohaISVL2n+t7GvA7Yb0JKmdiOOhDer6tOg4j/p4GTCEpOM87cjK7/Etg2bEI0x1v1zZD0GS+VIgyO9wRfDWDWIen4F2X323NRZHDoAOxahLD045ixBbPtOM1CLLSzE7V3B2WUAklA6k1X2zVquxcPdlp7Be4EKFXejvrmy2g/NOasT9LqnSwyQhMzJvHrS8JB9rPRDOjL1+1jwnJoJ24jqqPFPICBrHggDn2FpXpFzSRi/CIOXjtPiO3fOdLgzlCDb1CkAm7g9xAaPlbdbzfFjlDLXz3lJDr/LuCfriqLwU47vaaCTmfY+VycDZHD5uxf1hYOxdvNsbo+tZ+B2FaCQo+GDTsT1WcDkILSsSOEOtWYhhE9teqjp4zmxnPeT8JsqqtlAoJA1L1FLMUq+83ZnH+IbSzc2ypvZdbqAKK50j5+rEAkHIprno=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
